Documentation improvements
Kotlin/dataframe pull request #252
Opened 2023-02-06 17:10 UTC by koperagen

1. Added example for `add` use case that is supported but was missing from the docs
2. Changed nesting level for navigation inside topics so that it should be easier to navigate articles with lots of headers and, as an experiment, changed structure of add.md accordingly
3. Changed the structure of general navigation tree to bring attention to materials that seem neglected

2023-02-07 12:11 UTC, Jolanrensen requested changes

2023-02-07 12:11 UTC, Jolanrensen commented on examples/README.md
> +* [movies](idea-examples/movies) Using 3 different [access APIs](https://kotlin.github.io/dataframe/apilevels.html) to perform data cleaning task
Access APIs

2023-02-07 12:11 UTC, Jolanrensen commented on examples/README.md
> +Small artificial dataset used in [DataFrame API examples ](https://kotlin.github.io/dataframe/operations.html)
redundant space after "examples"

2023-02-07 21:50 UTC, koperagen commented on docs/StardustDocs/topics/operations.md
> +[//]: # (title: Operations overview)
Ok, i'll take it into account in the future c:

2023-02-08 11:33 UTC, Jolanrensen approved these changes

2023-02-08 14:07 UTC, merged

2023-02-08 14:07 UTC, koperagen commented
@Jolanrensen Thank you c: