Documentation updates
Kotlin/dataframe pull request #560
Opened 2024-01-15 12:54 UTC by koperagen

Let's try to put getting started snippets right in the README. One important selling point of the DataFrame is ease of working with data snippet you have: `read` API is straightforward and tooling helps discovering data with completion + types. Thus more emphasize on extension properties API.
Some other changes are focused on making things more explicit: why we show this and that

2024-01-16 16:25 UTC, Jolanrensen requested changes
Overall very nice! I like the extra comments in the examples a lot. Also I agree that the readme got too large and contained too much duplicate data. It's indeed better to redirect users to the docs for their specific platforms.
My repeating comments are mostly English related. I think that's extra important for first impressions (which is what the README often is for people), and I do see it could do some work in the untouched parts. I'll have a look later :). And a couple of times you say that "an extension properties API" is generated. I think that's a bit confusing. We have the "Extension Properties (Access) API", the "String (Access) API", etc. But the only thing that's generated are "extension properties", not an entire API. So that could propbably be rephrased better everywhere it's used.

2024-01-18 16:09 UTC, zaleslaw approved these changes

2024-01-18 16:09 UTC, zaleslaw commented
@koperagen could you please in your PR update the df version ctrl-c/ctrl-v to 0.12.1 in the docs?

2024-01-19 11:24 UTC, Jolanrensen commented
> @koperagen could you please in your PR update the df version ctrl-c/ctrl-v to 0.12.1 in the docs?

I'd use [VERSION] actually, otherwise we might forget it later

2024-01-19 18:42 UTC, koperagen commented on README.md
> +df["full_name"][0] // Indexing https://kotlin.github.io/dataframe/access.html
True, but i found it odd to have link for all operations as well :D Soo.. In this case the message it should convey is "hey, we have an API reference, check it out"

2024-01-22 12:21 UTC, koperagen commented on examples/idea-examples/json/build.gradle.kts
> -kotlin.sourceSets.getByName("main").kotlin.srcDir("build/generated/ksp/main/kotlin/")
Yes, works as planned

2024-01-22 12:25 UTC, koperagen commented
I updated to 0.12.1. I'd like to keep version number for peoples convenience

2024-01-22 12:27 UTC, merged