Sort df.compileTimeSchema() columns according to df.schema() so they're easier to compare
Kotlin/dataframe pull request #990
Opened 2024-12-06 12:35 UTC by koperagen

This is quality of life improvement. I print both schemas when i test implementation of join operation. I used to get compileTimeSchema in somewhat random order, it makes diff useless. Now when columns are present in both schemas, they will go in a definite order

2025-01-02 12:27 UTC, Jolanrensen commented on core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/schema.kt
> +internal fun DataFrameSchema.putColumnsOrder(order: MutableMap<ColumnPath, Int>, path: ColumnPath) {
kinda strange to see `DataFrameSchema` be the receiver. I'd expect the mutable map to be the receiver, since that's what you're modifying. That could also enable the notation:
```kt
val order = buildMap<ColumnPath, Int> {
    putColumnsInOrderOf(runtimeSchema, path)
}
```

2025-01-02 12:28 UTC, Jolanrensen commented on core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/schema.kt
> +internal fun DataFrameSchema.sorted(order: Map<ColumnPath, Int>, path: ColumnPath): DataFrameSchema {
here it's okay to have it as a receiver :) I'd only name it "sortedBy(order)" to be more expressive.

2025-01-02 12:29 UTC, Jolanrensen requested changes
just some small syntactical tips, otherwise lgtm :)

2025-01-29 11:48 UTC, koperagen commented on core/src/main/kotlin/org/jetbrains/kotlinx/dataframe/impl/api/schema.kt
> +internal fun DataFrameSchema.putColumnsOrder(order: MutableMap<ColumnPath, Int>, path: ColumnPath) {
true, i changed it

2025-01-29 13:42 UTC, merged